# Generated by Django 5.1.2 on 2024-10-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_exercise_image_exercise_video_url'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='exercise.exercise'),
        ),
    ]
