# Generated by Django 4.2 on 2024-10-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Описание категории питания')),
                ('popularity_score', models.IntegerField(default=0, help_text='Популярность категории, используется для сортировки')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='nutrition_management.nutritioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField(help_text='Количество калорий на порцию')),
                ('macronutrients', models.JSONField(help_text="Макроэлементы в формате JSON (например, {'protein': 10, 'fat': 5, 'carbohydrates': 20})")),
                ('serving_size', models.CharField(help_text="Размер порции, например, '100g' или '1 cup'", max_length=50)),
                ('is_vegan', models.BooleanField(default=False, help_text='Флаг, указывающий, является ли продукт веганским')),
                ('is_gluten_free', models.BooleanField(default=False, help_text='Флаг, указывающий, является ли продукт безглютеновым')),
                ('allergens', models.CharField(blank=True, help_text="Список аллергенов, если есть (например, 'орехи, молоко')", max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_items', to='nutrition_management.nutritioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Описание продукта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='nutrition_management.nutritioncategory')),
            ],
        ),
    ]
