# Generated by Django 5.1.2 on 2024-10-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('intensity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('calories', models.DecimalField(decimal_places=2, help_text='Estimated calories burned per minute', max_digits=5)),
                ('category', models.ManyToManyField(related_name='exercises', to='exercise.exercisecategory')),
                ('equipment', models.ManyToManyField(related_name='exercises', to='exercise.exerciseequipment')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercise.exerciselevel')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Описание плана тренировки')),
                ('duration_in_weeks', models.PositiveIntegerField(help_text='Длительность плана в неделях')),
                ('goal', models.CharField(help_text='Основная цель плана (например, потеря веса, набор мышц)', max_length=100)),
                ('level', models.ForeignKey(blank=True, help_text='Рекомендуемый уровень для этого плана', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercise.exerciselevel')),
                ('training_plan_exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_exercises', to='exercise.trainingplan')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата, на которую запланирована тренировка')),
                ('completed', models.BooleanField(default=False, help_text='Флаг выполнения тренировки')),
                ('notes', models.TextField(blank=True, help_text='Заметки о тренировке или прогрессе')),
                ('reminder_time', models.TimeField(blank=True, help_text='Время напоминания для тренировки', null=True)),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exercise.trainingplan')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(help_text='Количество подходов')),
                ('reps', models.IntegerField(help_text='Количество повторений в подходе')),
                ('rest_period', models.IntegerField(default=60, help_text='Время отдыха между подходами в секундах')),
                ('day', models.PositiveIntegerField(blank=True, help_text='День недели или дня плана для выполнения упражнения', null=True)),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки для выполнения упражнения')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_plans', to='exercise.exercise')),
            ],
        ),
    ]
